server {
    listen 443 ssl;
    server_name shop.shining-will.co.jp;

    ssl_certificate /etc/nginx/ssl/shop.crt;
    ssl_certificate_key /etc/nginx/ssl/shop.key;
    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_prefer_server_ciphers on;

    access_log /var/log/nginx/shop_access.log;
    error_log  /var/log/nginx/shop_error.log;

    location / {
        proxy_pass http://laravel.test:80;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_http_version 1.1;
        proxy_set_header Connection "";
    }
}

server {
    listen 80;
    server_name shop.shining-will.co.jp;
    return 301 https://$host$request_uri;
}
