name: Laravel Tests

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: shivammathur/setup-php@v2
        with:
          php-version: "8.3"
          coverage: none
          extensions: sqlite3,pdo_sqlite,mbstring

      - run: composer install --prefer-dist --no-interaction

      - name: Prepare Environment
        run: |
          cp .env.testing .env

      - run: php artisan key:generate

      - run: |
          touch database/testing.sqlite

      - run: chmod -R 777 storage bootstrap/cache

      - name: Clear Cache
        run: |
          php artisan config:clear
          php artisan cache:clear
          php artisan route:clear
          php artisan view:clear

      - name: Show Environment
        run: |
          php artisan env
          cat .env

      - name: Migrate
        env:
          APP_ENV: testing
          DB_CONNECTION: sqlite
          DB_DATABASE: database/testing.sqlite
        run: php artisan migrate:fresh

      - name: Run Tests
        env:
          APP_ENV: testing
          DB_CONNECTION: sqlite
          DB_DATABASE: database/testing.sqlite
        run: php artisan test
